USE MASTER 
GO

DROP DATABASE IF EXISTS
BMDB

CREATE DATABASE BMDB
GO



-- Movie Table
USE BMDB
GO
CREATE TABLE Movie(
	ID			INT				IDENTITY(1,1)		PRIMARY KEY,
	Title		VARCHAR(75)		NOT NULL,
	YEAR		INT				NOT NULL,
	Rating		VARCHAR(5)		NOT NULL,
	Director	VARCHAR(75)		NOT NULL,
	CONSTRAINT	UC_Movie		UNIQUE(Title, YEAR)
);
GO

USE BMDB 
GO
CREATE TABLE Actor(
	ID			INT				IDENTITY(1,1)		PRIMARY KEY,
	FirstName	VARCHAR(50)		NOT NULL,
	LastName	VARCHAR(50)		NOT NULL,
	Gender		VARCHAR(1)		NOT NULL,
	DOB			DATE			NOT NULL,
	CONSTRAINT	UC_Actor		Unique (FirstName, LastName, DOB)		
)
GO

USE BMDB 
GO
CREATE TABLE Credit(
	ID			INT				IDENTITY(1,1)			PRIMARY KEY,
	MovieID		INT				NOT NULL,
	ActorID		INT				NOT NULL,
	Role		VARCHAR(75)		NOT NULL,
	CONSTRAINT	UC_Credit		UNIQUE (MovieID, ActorID),
	CONSTRAINT  FK_CreditMovie	Foreign KEY (MovieID)	REFERENCES	Movie(ID),
	CONSTRAINT  FK_CreditActor	Foreign KEY (ActorID)	REFERENCES	Actor(ID)
)
GO

